### ISSUE TITLE
Custome data creation 

### ISSUE THREAD

**Issue by abhigoku10** [PointsCoder/GPT-Driver#4]
@PointsCoder  thanks for sharing the code base , i had a query when ur creating the data with UNIAD repo what is the modification done for training it for gptdriver repo as i see there i missing keys values in the dict of the complete dataset .. 
thanks in advance

**Comment by PointsCoder** [comment]
@abhigoku10 Not sure what is the question. Could you please elaborate it with more details?

**Comment by abhigoku10** [comment]
@PointsCoder  closing this thread as it answers in the #3
